name:                hscc
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Zylphrex/hscc
license:             MIT
author:              Tony
maintainer:          zylphrex@gmail.com
copyright:           2021 Tony
category:            Compiler
extra-source-files:
  - README.md

library:
  source-dirs:      src

dependencies:
  - base      >= 4.7 && < 5
  - filepath  >= 1.4 && < 1.5
  - mtl       >= 2.2 && < 2.3
  - pretty    >= 1.1 && < 1.2

executables:
  hscc:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - hscc

tests:
  hscc-test:
    source-dirs:      test
    main:             Spec.hs
    ghc-options:      -Wall
    dependencies:
      - hscc
      - hpc-codecov  >= 0.2 && < 0.3
      - hspec        >= 2.0
